// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a/b/c.proto

module a.c;

import google.protobuf;

enum protocVersion = 3012004;

class A
{

    static class B
    {
        @Proto(1) int i = protoDefaultValue!(int);
    }
}

class C
{
    @Proto(1) A.B b = protoDefaultValue!(A.B);
}
