// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a/b/c.proto

module a.c;

import google.protobuf;

enum protocVersion = 3012004;

class A
{

    static class B
    {
        @Proto(1) int i = protoDefaultValue!int;
    }
}

class C
{
    @Proto(1) A.B b = protoDefaultValue!(A.B);
    enum OCase
    {
        oNotSet = 0,
        ob = 2,
        oi = 3,
    }
    OCase _oCase = OCase.oNotSet;
    @property OCase oCase() { return _oCase; }
    void clearO() { _oCase = OCase.oNotSet; }
    @Oneof("_oCase") union
    {
        @Proto(2) A.B _ob = protoDefaultValue!(A.B); mixin(oneofAccessors!_ob);
        @Proto(3) int _oi; mixin(oneofAccessors!_oi);
    }
}
