// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/api.proto

module google.protobuf.api;

import google.protobuf;
import google.protobuf.source_context;
import google.protobuf.type;

class Api
{
    @Proto(1) string name = defaultValue!string;
    @Proto(2) Method[] methods = defaultValue!(Method[]);
    @Proto(3) Option[] options = defaultValue!(Option[]);
    @Proto(4) string version_ = defaultValue!string;
    @Proto(5) SourceContext sourceContext = defaultValue!SourceContext;
    @Proto(6) Mixin[] mixins = defaultValue!(Mixin[]);
    @Proto(7) Syntax syntax = defaultValue!Syntax;
}

class Method
{
    @Proto(1) string name = defaultValue!string;
    @Proto(2) string requestTypeUrl = defaultValue!string;
    @Proto(3) bool requestStreaming = defaultValue!bool;
    @Proto(4) string responseTypeUrl = defaultValue!string;
    @Proto(5) bool responseStreaming = defaultValue!bool;
    @Proto(6) Option[] options = defaultValue!(Option[]);
    @Proto(7) Syntax syntax = defaultValue!Syntax;
}

class Mixin
{
    @Proto(1) string name = defaultValue!string;
    @Proto(2) string root = defaultValue!string;
}
