// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/api.proto

module google.protobuf.api;

import google.protobuf;
import google.protobuf.source_context;
import google.protobuf.type;

class Api
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) Method[] methods = protoDefaultValue!(Method[]);
    @Proto(3) Option[] options = protoDefaultValue!(Option[]);
    @Proto(4) string version_ = protoDefaultValue!string;
    @Proto(5) SourceContext sourceContext = protoDefaultValue!SourceContext;
    @Proto(6) Mixin[] mixins = protoDefaultValue!(Mixin[]);
    @Proto(7) Syntax syntax = protoDefaultValue!Syntax;
}

class Method
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) string requestTypeUrl = protoDefaultValue!string;
    @Proto(3) bool requestStreaming = protoDefaultValue!bool;
    @Proto(4) string responseTypeUrl = protoDefaultValue!string;
    @Proto(5) bool responseStreaming = protoDefaultValue!bool;
    @Proto(6) Option[] options = protoDefaultValue!(Option[]);
    @Proto(7) Syntax syntax = protoDefaultValue!Syntax;
}

class Mixin
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) string root = protoDefaultValue!string;
}
