// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/source_context.proto

module google.protobuf.source_context;

import google.protobuf;

class SourceContext
{
    @Proto(1) string fileName = protoDefaultValue!string;
}
