// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

module google.protobuf.type;

import google.protobuf;
import google.protobuf.any;
import google.protobuf.source_context;

class Type
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) Field[] fields = protoDefaultValue!(Field[]);
    @Proto(3) string[] oneofs = protoDefaultValue!(string[]);
    @Proto(4) Option[] options = protoDefaultValue!(Option[]);
    @Proto(5) SourceContext sourceContext = protoDefaultValue!SourceContext;
    @Proto(6) Syntax syntax = protoDefaultValue!Syntax;
}

class Field
{
    @Proto(1) Kind kind = protoDefaultValue!Kind;
    @Proto(2) Cardinality cardinality = protoDefaultValue!Cardinality;
    @Proto(3) int number = protoDefaultValue!int;
    @Proto(4) string name = protoDefaultValue!string;
    @Proto(6) string typeUrl = protoDefaultValue!string;
    @Proto(7) int oneofIndex = protoDefaultValue!int;
    @Proto(8) bool packed = protoDefaultValue!bool;
    @Proto(9) Option[] options = protoDefaultValue!(Option[]);
    @Proto(10) string jsonName = protoDefaultValue!string;
    @Proto(11) string defaultValue = protoDefaultValue!string;

    enum Kind
    {
        TYPE_UNKNOWN = 0,
        TYPE_DOUBLE = 1,
        TYPE_FLOAT = 2,
        TYPE_INT64 = 3,
        TYPE_UINT64 = 4,
        TYPE_INT32 = 5,
        TYPE_FIXED64 = 6,
        TYPE_FIXED32 = 7,
        TYPE_BOOL = 8,
        TYPE_STRING = 9,
        TYPE_GROUP = 10,
        TYPE_MESSAGE = 11,
        TYPE_BYTES = 12,
        TYPE_UINT32 = 13,
        TYPE_ENUM = 14,
        TYPE_SFIXED32 = 15,
        TYPE_SFIXED64 = 16,
        TYPE_SINT32 = 17,
        TYPE_SINT64 = 18,
    }

    enum Cardinality
    {
        CARDINALITY_UNKNOWN = 0,
        CARDINALITY_OPTIONAL = 1,
        CARDINALITY_REQUIRED = 2,
        CARDINALITY_REPEATED = 3,
    }
}

class Enum
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) EnumValue[] enumvalue = protoDefaultValue!(EnumValue[]);
    @Proto(3) Option[] options = protoDefaultValue!(Option[]);
    @Proto(4) SourceContext sourceContext = protoDefaultValue!SourceContext;
    @Proto(5) Syntax syntax = protoDefaultValue!Syntax;
}

class EnumValue
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) int number = protoDefaultValue!int;
    @Proto(3) Option[] options = protoDefaultValue!(Option[]);
}

class Option
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) Any value = protoDefaultValue!Any;
}

enum Syntax
{
    SYNTAX_PROTO2 = 0,
    SYNTAX_PROTO3 = 1,
}
