// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

module google.protobuf.type;

import google.protobuf;
import google.protobuf.any;
import google.protobuf.source_context;

class Type
{
    @Proto(1) string name = defaultValue!string;
    @Proto(2) Field[] fields = defaultValue!(Field[]);
    @Proto(3) string[] oneofs = defaultValue!(string[]);
    @Proto(4) Option[] options = defaultValue!(Option[]);
    @Proto(5) SourceContext sourceContext = defaultValue!SourceContext;
    @Proto(6) Syntax syntax = defaultValue!Syntax;
}

class Field
{
    @Proto(1) Kind kind = defaultValue!Kind;
    @Proto(2) Cardinality cardinality = defaultValue!Cardinality;
    @Proto(3) int number = defaultValue!int;
    @Proto(4) string name = defaultValue!string;
    @Proto(6) string typeUrl = defaultValue!string;
    @Proto(7) int oneofIndex = defaultValue!int;
    @Proto(8) bool packed = defaultValue!bool;
    @Proto(9) Option[] options = defaultValue!(Option[]);
    @Proto(10) string jsonName = defaultValue!string;
    @Proto(11) string defaultValue = defaultValue!string;

    enum Kind
    {
        TYPE_UNKNOWN = 0,
        TYPE_DOUBLE = 1,
        TYPE_FLOAT = 2,
        TYPE_INT64 = 3,
        TYPE_UINT64 = 4,
        TYPE_INT32 = 5,
        TYPE_FIXED64 = 6,
        TYPE_FIXED32 = 7,
        TYPE_BOOL = 8,
        TYPE_STRING = 9,
        TYPE_GROUP = 10,
        TYPE_MESSAGE = 11,
        TYPE_BYTES = 12,
        TYPE_UINT32 = 13,
        TYPE_ENUM = 14,
        TYPE_SFIXED32 = 15,
        TYPE_SFIXED64 = 16,
        TYPE_SINT32 = 17,
        TYPE_SINT64 = 18,
    }

    enum Cardinality
    {
        CARDINALITY_UNKNOWN = 0,
        CARDINALITY_OPTIONAL = 1,
        CARDINALITY_REQUIRED = 2,
        CARDINALITY_REPEATED = 3,
    }
}

class Enum
{
    @Proto(1) string name = defaultValue!string;
    @Proto(2) EnumValue[] enumvalue = defaultValue!(EnumValue[]);
    @Proto(3) Option[] options = defaultValue!(Option[]);
    @Proto(4) SourceContext sourceContext = defaultValue!SourceContext;
    @Proto(5) Syntax syntax = defaultValue!Syntax;
}

class EnumValue
{
    @Proto(1) string name = defaultValue!string;
    @Proto(2) int number = defaultValue!int;
    @Proto(3) Option[] options = defaultValue!(Option[]);
}

class Option
{
    @Proto(1) string name = defaultValue!string;
    @Proto(2) Any value = defaultValue!Any;
}

enum Syntax
{
    SYNTAX_PROTO2 = 0,
    SYNTAX_PROTO3 = 1,
}
