name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        dc: [dmd-latest, ldc-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Build & Test
        run: |
          dub build --compiler=$DC
          dub test --compiler=$DC
          dub build :protoc-gen-d --compiler=$DC

      - name: Run Golden Tests
        run: |
          cd test
          ./run.sh

      - name: Install automake
        if: runner.os == 'macOS'
        run: |
          brew install automake

      - name: Run Conformance Tests
        run: |
          cd conformance && ./run-conformance-test.sh
          echo "$(pwd)/protobuf/src" >> $GITHUB_PATH
          echo "PROTO_PATH=-I. -I$(pwd)/protobuf/src" >> $GITHUB_ENV

      - name: Run protoc-gen-d Examples
        run: |
          cd examples
          dub build :add_person --compiler=$DC
          dub build :list_people --compiler=$DC
